ci: enable UB sanitizer

diff --git a/.github/workflows/ci-scripts-build.yml b/.github/workflows/ci-scripts-build.yml
--- a/.github/workflows/ci-scripts-build.yml
+++ b/.github/workflows/ci-scripts-build.yml
@@ -92,6 +92,13 @@ jobs:
             configuration: default
             base: "7.0"
 
+          - name: Native Linux with clang ubsan
+            os: ubuntu-latest
+            cmp: clang
+            configuration: default
+            base: "7.0"
+            extra: "CMD_CFLAGS=-fsanitize=undefined CMD_CXXFLAGS=-fsanitize=undefined CMD_LDFLAGS=-fsanitize=undefined"
+
           - name: Native Linux with libevent stable
             os: ubuntu-latest
             cmp: gcc
@@ -167,10 +174,25 @@ jobs:
       run: find bundle/usr lib -name '*.so' -print0 | xargs -0 readelf -d bin/linux-*/pvxinfo
     - name: Host info
       run: python .ci/cue.py --add-path "{TOP}/bin/{EPICS_HOST_ARCH}" --add-path "{TOP}/bundle/usr/{EPICS_HOST_ARCH}/lib" exec pvxinfo -D
+    - name: Test env setup
+      run: echo "UBSAN_OPTIONS=log_path=$PWD/UBSAN:suppressions=$PWD/.ci-local/ubsan.supp:report_error_type=1:print_stacktrace=1" >> $GITHUB_ENV
     - name: Run main module tests
       run: python -m ci_core_dumper exec python .ci/cue.py -T 5M --add-path "{TOP}/bundle/usr/{EPICS_HOST_ARCH}/lib" test
     - name: Collect and show test results
+      if: ${{ always() }}
       run: python .ci/cue.py test-results
+    - name: Show UBSAN logs
+      shell: bash
+      if: ${{ always() }}
+      run: |
+        ret=0
+        for ff in `find . -name 'UBSAN*'`
+        do
+          echo "==== $ff ===="
+          cat "$ff"
+          ret=1
+        done
+        exit $ret
     - name: CDT Check
       run: ./.ci-local/cdt-check.sh
       if: runner.os == 'Linux'
